name: clangd-opt-git-alpine

on: [push, workflow_dispatch]

env:
  CLICOLOR_FORCE: 1

jobs:
  clangd:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Alpine Linux
      uses: jirutka/setup-alpine@v1
      with:
        branch: latest-stable
        packages: >
          clang19
          clang19-extra-tools
          compiler-rt
          cmake
          git
          libc++-dev
          libc++-static
          llvm19
          llvm-libunwind-static
          mold
          musl-dev
          patch
          ninja-build
          ninja-is-really-ninja
          python3
    - name: checkout
      run: |
        git clone --depth 1 --branch llvmorg-20.1.1 https://github.com/llvm/llvm-project.git
        git clone https://aur.archlinux.org/clangd-opt-git.git
        cd clangd-opt-git
        git checkout 7c4a916467740257887a95b4c55069486d6722a1
        cd ..
      shell: alpine.sh {0}
    - name: patch
      run: |
        cd llvm-project
        patch -p1 -i ../clangd-opt-git/hover-doxygen-trunk.patch
        patch -p1 -i ../clangd-opt-git/doxygen-extra-render-trunk.patch
        patch -p1 -i ../clangd-opt-git/doxygen-more-fields.patch
        patch -p1 -i ../clangd-opt-git/hover-resolve-forward-params.patch
        patch -p1 -i ../clangd-opt-git/hover-bit-fields-mask.patch
        patch -p1 -i ../clangd-opt-git/hover-hex-formats.patch
        patch -p1 -i ../clangd-opt-git/hover-no-defs.patch
        patch -p1 -i ../clangd-opt-git/hover-record-paddings.patch
        patch -p1 -i ../clangd-opt-git/lsp-preprocessor-folding.patch
        patch -p1 -i ../clangd-opt-git/postfix-completion-trunk.patch
        patch -p1 -i ../clangd-opt-git/refactor-extract-function.patch
        patch -p1 -i ../clangd-opt-git/inlay-hints-paddings.patch
        patch -p1 -i ../clangd-opt-git/inlay-hints-blockend-linelimit10.patch
        cd ..
      shell: alpine.sh {0}
    - name: build
      run: |
        mkdir build
        cd build
        cmake -B . -S ../llvm-project/llvm -G Ninja -DCMAKE_C_COMPILER=clang-19 -DCMAKE_CXX_COMPILER=clang++-19 -DCMAKE_INSTALL_PREFIX=/opt/clangd-opt-git -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra" -DLLVM_HOST_TRIPLE="x86_64-alpine-linux-musl" -DLLVM_DEFAULT_TARGET_TRIPLE="x86_64-alpine-linux-musl" -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=mold -stdlib=libc++ -rtlib=compiler-rt -static -lc++abi -lunwind" -DCMAKE_CXX_FLAGS="-stdlib=libc++"
        cmake --build . --target clangd
        llvm-strip --strip-all bin/clangd
        cd ..
        rm -rf clangd-opt-git
        mkdir clangd-opt-git
        cd clangd-opt-git
        mkdir bin
        cp ../build/bin/clangd ./bin/
        mkdir lib
        cd lib
        cp --recursive ../../build/lib/clang ./
        cd ..
        cd ..
      shell: alpine.sh {0}
    - name: publish
      uses: actions/upload-artifact@v4
      with:
        name: clangd-opt-git
        if-no-files-found: error
        path: clangd-opt-git
